CREATE TABLE IF NOT EXISTS category ( CAT_ID INT NOT NULL,
CAT_NAME VARCHAR(20) NOT NULL, PRIMARY KEY (CAT_ID)
);

INSERT INTO CATEGORY VALUES( 1,"BOOKS");
INSERT INTO CATEGORY VALUES(2,"GAMES"); 
INSERT INTO CATEGORY VALUES(3,"GROCERIES"); 
INSERT INTO CATEGORY VALUES (4,"ELECTRONICS"); 
INSERT INTO CATEGORY VALUES(5,"CLOTHES");